[pytest]
filterwarnings=
    ignore:torch\.onnx\.dynamo_export:DeprecationWarning
    ignore:label\(\) is deprecated\. Use is_required\(\) or is_repeated\(\) instead\.:DeprecationWarning:a2a\.utils\.proto_utils
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
