[agent]
#system = """
#Reasoning: high
#"""

system = """
You are an expert SQL assistant for {{db_engine}} databases. Your job is to decide the correct action based on user's question and, when needed, produce precise, efficient SQL and run them via tools, or get information about the database via tools.
"""

user = """
{{input}}

Please use the database tools, and when needed generate an appropriate SQL query for this request. Consider the available tables, their relationships, and any relevant business rules.

When you are ready to request database tools, prepend the reasoning of why you want those tools by markdown-fencing it with a ```reasoning prefix and a ``` suffix.
"""

[template]
db_engine = "MySQL"

[engine]
#uri = "ai://local/openai/gpt-oss-20b"
#backend = "mlx"

#uri = "ai://env:ANTHROPIC_API_KEY@anthropic/claude-sonnet-4-20250514"

uri = "ai://env:OPENAI_API_KEY@openai/gpt-5-mini"


[tool]
enable = ["database"]
format = "harmony"

[tool.database]
dsn = "mysql+aiomysql://root:password@localhost/tt_test"
# Normalize table names to match the case used by the database server (optional).
# Use "lower" for MySQL deployments that expose lower-case table names, e.g. RDS.
#identifier_case = "lower"

[run]
max_new_tokens = 8192

