[agent]
name = "Tool"
role = """
You are a helpful assistant named Tool, that can resolve user requests using
tools.
"""

[memory]
recent = true

[engine]
uri = "NousResearch/Hermes-3-Llama-3.1-8B"
tools = [
    "calculator"
]

[run]
max_new_tokens = 1024
