"""Test the exact Phase 4 reasoning-summary acceptance inventory."""

from typing import Any, cast

from reasoning_summary_script_loader import load_reasoning_summary_script

_ACCEPTANCE_SCRIPT = load_reasoning_summary_script(
    "verify_reasoning_summary_acceptance"
)
_PHASE4_DIMENSION = "phase 4 OpenAI multipart summary state machine"
_SUMMARY_TEST = "tests/model/nlp/vendor_openai_reasoning_summary_test.py::"
_OPENAI_TEST = "tests/model/nlp/vendor_openai_test.py::OpenAITestCase::"
_PHASE4_NODE_IDS = (
    (
        "tests/reasoning_summary_phase4_manifest_test.py::"
        "test_phase4_acceptance_manifest_pins_exact_catalog"
    ),
    f"{_SUMMARY_TEST}test_summary_delta_emits_immediately",
    f"{_SUMMARY_TEST}test_summary_delta_does_not_wait_for_later_output",
    f"{_SUMMARY_TEST}test_summary_delta_uses_canonical_reasoning",
    (
        f"{_SUMMARY_TEST}"
        "test_summary_delta_preserves_lossless_whitespace_and_identity"
    ),
    f"{_SUMMARY_TEST}test_summary_stream_accepts_dict_and_sdk_event_shapes",
    f"{_SUMMARY_TEST}test_part_completion_does_not_close_reasoning",
    f"{_SUMMARY_TEST}test_reasoning_item_has_at_most_one_response_done",
    f"{_SUMMARY_TEST}test_multipart_summary_preserves_emission_order",
    f"{_SUMMARY_TEST}test_summary_index_is_preserved",
    (
        f"{_SUMMARY_TEST}"
        "test_sparse_summary_indices_preserve_live_then_fallback_order"
    ),
    f"{_SUMMARY_TEST}test_empty_summary_is_invisible",
    f"{_SUMMARY_TEST}test_empty_summary_preserves_tools_and_answer",
    f"{_SUMMARY_TEST}test_empty_summary_is_operationally_invisible",
    f"{_SUMMARY_TEST}test_completed_item_fallback_is_deduplicated_per_part",
    f"{_SUMMARY_TEST}test_zero_length_delta_remains_fallback_eligible",
    f"{_SUMMARY_TEST}test_mixed_streamed_and_fallback_parts_emit_once",
    f"{_SUMMARY_TEST}test_summary_completion_duplicates_are_idempotent",
    f"{_SUMMARY_TEST}test_reasoning_output_item_done_never_emits_answer_text",
    (
        f"{_SUMMARY_TEST}"
        "test_reasoning_output_item_done_records_replay_exactly_once"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_interoperates_with_one_and_multiple_tool_calls"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_followed_by_final_answer_keeps_channels_separate"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_native_only_and_mixed_reasoning_preserve_representations"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_multiple_summary_continuations_preserve_response_local_identity"
    ),
    f"{_SUMMARY_TEST}test_visible_summary_disables_retry",
    f"{_SUMMARY_TEST}test_previsible_retry_resets_multipart_state",
    (
        f"{_SUMMARY_TEST}"
        "test_summary_negative_transition_matrix_emits_one_structured_error"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_index_type_matrix_emits_one_structured_error"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_rejects_non_string_delta_with_safe_diagnostics"
    ),
    f"{_SUMMARY_TEST}test_summary_identity_conflicts_are_content_free",
    (
        f"{_SUMMARY_TEST}"
        "test_summary_adapter_error_provider_payload_is_not_projected"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_provider_failure_and_incomplete_balance_prefix"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_response_incomplete_maps_safe_error_after_prefix"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_summary_consumer_aclose_yields_nothing_and_closes_once"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_summary_cancel_pending_pull_closes_once_without_late_output"
    ),
    f"{_OPENAI_TEST}test_summary_cancellation_boundaries_are_deterministic",
    (
        f"{_OPENAI_TEST}"
        "test_summary_cancellation_during_retry_delay_starts_no_retry"
    ),
    f"{_OPENAI_TEST}test_summary_stream_is_pull_driven_without_read_ahead",
    f"{_SUMMARY_TEST}test_summary_state_is_isolated_per_stream_instance",
    f"{_SUMMARY_TEST}test_private_capable_client_streams_summary_end_to_end",
    f"{_SUMMARY_TEST}test_phase4_public_summary_capability_remains_dormant",
    (
        f"{_SUMMARY_TEST}"
        "test_summary_response_incomplete_rejects_untrusted_metadata"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_provider_payload_never_reaches_outward_surfaces"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_hostile_summary_sdk_access_is_structured_and_content_free"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_live_summary_terminal_and_cleanup_echoes_are_sanitized"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_source_exhaustion_beats_private_cleanup_failure"
    ),
    f"{_SUMMARY_TEST}test_private_replay_cancellation_event_is_content_free",
    (
        f"{_SUMMARY_TEST}"
        "test_openai_sdk_rejects_invented_provider_cancellation_event"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_second_event_type_access_failure_cannot_leak_provider_data"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_reasoning_item_cannot_flip_to_message_after_completion"
    ),
    f"{_SUMMARY_TEST}test_message_item_cannot_flip_to_reasoning",
    f"{_SUMMARY_TEST}test_reasoning_item_cannot_flip_to_tool_call",
    f"{_SUMMARY_TEST}test_output_item_id_cannot_move_to_another_output_index",
    (
        f"{_SUMMARY_TEST}"
        "test_output_index_cannot_be_reassigned_to_another_item_id"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_output_item_identity_lock_allows_distinct_message_and_tool"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_event_type_string_subclass_is_rejected_without_method_calls"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_sdk_and_dict_item_id_string_subclasses_are_content_free"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_summary_text_string_subclasses_are_rejected_without_calls"
    ),
    f"{_SUMMARY_TEST}test_duplicate_item_events_require_exact_builtin_type",
    (
        f"{_SUMMARY_TEST}"
        "test_item_type_subclass_is_rejected_before_payload_sanitization"
    ),
    f"{_SUMMARY_TEST}test_non_reasoning_identities_reject_every_summary_event",
    (
        f"{_SUMMARY_TEST}"
        "test_stateless_reasoning_identity_rejects_every_summary_event"
    ),
    f"{_SUMMARY_TEST}test_safe_adapter_error_does_not_stringify_wrapped_error",
    (
        f"{_SUMMARY_TEST}"
        "test_standalone_reasoning_done_latches_private_output_without_replay"
    ),
    f"{_SUMMARY_TEST}test_malformed_reasoning_added_latches_before_cleanup",
    f"{_SUMMARY_TEST}test_duplicate_standalone_reasoning_done_records_once",
    (
        f"{_SUMMARY_TEST}"
        "test_conflicting_standalone_reasoning_done_is_content_free"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_standalone_reasoning_fingerprints_clear_on_terminal_paths"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_standalone_reasoning_done_closes_identity_to_late_events"
    ),
    f"{_SUMMARY_TEST}test_terminal_snapshot_cannot_relabel_reasoning_identity",
    (
        f"{_SUMMARY_TEST}"
        "test_terminal_snapshot_allows_distinct_message_and_legacy_text"
    ),
    f"{_SUMMARY_TEST}test_text_events_cannot_relabel_non_text_identity",
    (
        f"{_SUMMARY_TEST}"
        "test_tool_argument_events_cannot_relabel_non_tool_identity"
    ),
    f"{_SUMMARY_TEST}test_unknown_output_item_done_never_emits_answer_or_tool",
    (
        f"{_SUMMARY_TEST}"
        "test_nested_custom_tool_shape_requires_matching_outer_type"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_tool_argument_events_enforce_function_custom_subtype"
    ),
    f"{_SUMMARY_TEST}test_native_reasoning_events_require_reasoning_identity",
    (
        f"{_SUMMARY_TEST}"
        "test_private_output_type_matrix_preserves_primary_error_over_cleanup"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_present_output_fields_and_semantic_identities_are_strict"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_message_content_types_and_terminal_aggregate_are_authoritative"
    ),
    f"{_SUMMARY_TEST}test_semantic_first_locks_are_monotonic",
    f"{_SUMMARY_TEST}test_tool_identity_and_name_registry_is_one_to_one",
    (
        f"{_SUMMARY_TEST}"
        "test_tool_argument_final_values_reconcile_before_side_effects"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_output_status_and_closed_channel_transitions_are_strict"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_reasoning_duplicates_require_exact_replay_significant_fields"
    ),
    f"{_SUMMARY_TEST}test_text_content_index_is_strict_and_stable",
    f"{_SUMMARY_TEST}test_text_and_terminal_identity_conflicts_are_strict",
    (
        f"{_SUMMARY_TEST}"
        "test_semantic_tool_metadata_refines_and_rejects_name_conflicts"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_tool_argument_closure_and_no_delta_fallback_are_consistent"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_reasoning_fingerprint_sdk_fallback_and_retention_errors"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_private_output_classifier_handles_every_unreadable_boundary"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_terminal_aggregate_and_message_field_shapes_are_strict"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_terminal_tool_without_identity_and_malformed_tool_id_are_safe"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_native_lock_without_summary_state_rejects_summary_parts"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_empty_native_reasoning_delta_is_invisible_and_locks_identity"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_private_provider_payload_strips_reasoning_replay_fields"
    ),
    f"{_OPENAI_TEST}test_stream_aclose_drops_late_summary_after_blocked_pull",
    f"{_OPENAI_TEST}test_stream_aclose_drops_late_tool_after_blocked_pull",
    f"{_OPENAI_TEST}test_stream_aclose_drops_buffered_tool_events",
    f"{_OPENAI_TEST}test_stream_aclose_drops_buffered_terminal_frames",
    f"{_OPENAI_TEST}test_stream_aclose_interrupts_blocked_retry_delay",
    f"{_OPENAI_TEST}test_stream_cancel_interrupts_pending_pull_with_terminal",
    f"{_OPENAI_TEST}test_canonical_guard_drops_item_returned_during_aclose",
    f"{_OPENAI_TEST}test_provider_events_reject_concurrent_active_consumer",
    (
        f"{_OPENAI_TEST}"
        "test_vendor_wrapper_aggregates_nested_and_owner_close_errors"
    ),
    f"{_OPENAI_TEST}test_suppressed_task_cancellation_cannot_emit_tool_events",
    (
        f"{_OPENAI_TEST}"
        "test_suppressed_retry_factory_cancellation_closes_replacement"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_stream_cancel_during_retry_factory_closes_replacement"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_stream_aclose_during_retry_factory_closes_replacement"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_terminal_snapshots_revalidate_without_replaying_done_items"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_done_item_conflicts_are_rejected_before_duplicate_side_effects"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_terminal_output_cannot_omit_or_conflict_with_completed_items"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_preparse_privacy_rejects_hostile_container_graph_without_calls"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_preparse_privacy_covers_private_terminal_and_cleanup_matrix"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_non_private_omitted_summary_payload_remains_compatible"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_native_reasoning_content_indices_reconcile_and_interleave"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_native_reasoning_content_index_and_done_conflicts_are_strict"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_zero_length_sparse_part_requires_completed_array_position"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_real_async_generator_close_awaits_suppressed_pull_unwind"
    ),
    f"{_OPENAI_TEST}test_stream_aclose_between_pulls_does_not_cancel_consumer",
    (
        f"{_OPENAI_TEST}"
        "test_real_async_generator_cancel_emits_one_cancelled_terminal"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_provider_terminal_scrubs_state_and_closes_source_pre_yield"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_client_close_attribute_failures_are_sanitized_and_release"
    ),
    f"{_OPENAI_TEST}test_cancel_between_pulls_never_reenters_closed_provider",
    (
        f"{_SUMMARY_TEST}"
        "test_native_content_indices_do_not_define_canonical_segments"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_unified_terminal_finalizer_applies_cleanup_precedence"
    ),
    f"{_SUMMARY_TEST}test_eof_cleanup_failure_rolls_back_replay_success",
    (
        f"{_SUMMARY_TEST}"
        "test_private_provider_failure_terminal_scrubs_live_frames"
    ),
    f"{_SUMMARY_TEST}test_replay_owner_error_terminal_scrubs_live_frames",
    (
        f"{_SUMMARY_TEST}"
        "test_failed_and_incomplete_outputs_revalidate_completed_items"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_provider_events_has_one_typed_terminal_yield_epilogue"
    ),
    (
        f"{_SUMMARY_TEST}"
        "test_private_cancel_cleanup_failure_preserves_stored_terminal"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_provider_events_owner_rejects_consumer_between_yields"
    ),
    (
        f"{_OPENAI_TEST}"
        "test_direct_normalizer_preserves_canonical_wrapper_contract"
    ),
    f"{_OPENAI_TEST}test_external_finish_waits_for_suppressed_pull_unwind",
    f"{_OPENAI_TEST}test_external_finish_serializes_with_terminal_cleanup",
    f"{_OPENAI_TEST}test_consumer_cancel_during_terminal_cleanup_rolls_back",
    f"{_SUMMARY_TEST}test_success_terminal_commits_output_sink_checkpoint",
    f"{_SUMMARY_TEST}test_present_malformed_terminal_output_is_fail_closed",
    f"{_OPENAI_TEST}test_cancel_detaches_before_single_cleanup_invocation",
)


def test_phase4_acceptance_manifest_pins_exact_catalog() -> None:
    manifest = cast(
        Any,
        _ACCEPTANCE_SCRIPT.load_manifest(
            _ACCEPTANCE_SCRIPT.default_manifest_path()
        ),
    )

    assert manifest.active_phase == 4
    assert manifest.dimensions[_PHASE4_DIMENSION] == _PHASE4_NODE_IDS
    assert len(_PHASE4_NODE_IDS) == 140
    assert len(manifest.node_ids) == 289
    assert len(manifest.node_ids) == len(set(manifest.node_ids))
