name: Unit Tests

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      ignore_venv_cache:
        description: 'Ignore cached venv when running tests.'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}‑${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    env:
      IGNORE_VENV_CACHE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ignore_venv_cache == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.11', '3.12']

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }} + Poetry cache
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip
        run: pip install --upgrade pip

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-v8

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        if: env.IGNORE_VENV_CACHE != 'true'
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-v8-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        id: install-deps
        if: env.IGNORE_VENV_CACHE == 'true' || steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --extras "test"

      - name: Install mlx
        run: poetry run pip install "mlx[cpu]==0.28.0" "mlx-lm==0.26.3"

      - name: Install BeautifulSoup and pypdf
        run: poetry run pip install "beautifulsoup4==4.14.2" "pypdf==6.1.1"

      - name: Run tests with coverage analysis
        run: poetry run pytest --cov=src/ --cov-report=xml

      - name: Upload coverage to Coveralls
        continue-on-error: true
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: cobertura
          file: coverage.xml
          flag-name: unit test
          parallel: true
          fail-on-error: true

  finish:
    if: ${{ always() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
