name: Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install poetry
        run: pip install poetry
      - name: Install poetry test dependencies
        run: poetry sync --extras "test"
      - name: Install pytest coverage analyzer
        run: poetry run pip install pytest-cov
      - name: Run tests with coverage analysis
        run: poetry run pytest --verbose -s --cov --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
